### ISSUE TITLE
Should first check `headerSent` flag in `Cookies.prototype.set`?

### ISSUE THREAD

**Issue by jiajianrong** [pillarjs/cookies#100]
when using `cookies.set()`, who is supposed to check if the response header is already sent? the developer or `Cookies.prototype.set`? Thanks.

**Comment by dougwilson** [comment]
The developer. Having it blow up like it does now makes it very obvious that the cookie is not going to set.

**Comment by vsviridov** [comment]
If the cookie signature is incorrect, `cookies` seems to be calling setHeader without checking if headers were sent already
