### ISSUE TITLE
cookie value NOT decoded

### ISSUE THREAD

**Issue by sophister** [pillarjs/cookies#105]
Hi, this library does NOT use `decodeURIComponent` as default method to decode cookie value in `Cookies.prototype.get` method.  

The [cookie-parser](https://github.com/expressjs/cookie-parser) used by `express.js`, uses [cookie](https://github.com/jshttp/cookie/blob/master/index.js#L78) to parse cookies, which uses `decodeURIComponent` as default function to decode cookie values.

Why this cookie library does NOT **decode** cookie value automatically?

**Comment by dougwilson** [comment]
This is by design. Decoding / encoding automatically causing interop issues with other languages. This library only operates on the raw values as it's design principle.
