### ISSUE TITLE
Secure Bug

### ISSUE THREAD

**Issue by willin** [pillarjs/cookies#117]
https://github.com/pillarjs/cookies/blob/master/index.js#L94

Error: Cannot send secure cookie over unencrypted connection

but my request is through https.  

koa app, use koa-session, nginx http2.

when i just delete this line, it works well

**Comment by panva** [comment]
```js
app.proxy = true
```

This makes your koa app trust the `x-forwarded-*` headers set by your nginx (check that you set them) which in turns makes the `ctx.secure` evaluate to true this non-issue (its a feature) goes away.

**Comment by dougwilson** [comment]
Yep, exactly @panva :) @willin you can read about it all in our docs https://github.com/pillarjs/cookies/blob/master/README.md#secure-cookies

**Comment by willin** [comment]
thx
