### ISSUE TITLE
Cookie expires time is different for chrome

### ISSUE THREAD

**Issue by shunnmugam** [pillarjs/cookies#123]
when i store cookies using chrome and firefox
1) expire time for chrome : 2020-03-05T18:27:52.900Z
2) expire time for firefox : Thu, 05 Mar 2020 12:44:52 GMT

**Comment by jonchurch** [comment]
Can you provide steps to reproduce or a [Minimal Reproducible Example?](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by dougwilson** [comment]
Closing due to no response.
