### ISSUE TITLE
Max length on cookie

### ISSUE THREAD

**Issue by kevinsimper** [pillarjs/cookies#125]
I have a problem with Chrome where it complains about a cookie is Invalid:

![image](https://user-images.githubusercontent.com/1126497/82759042-d46c5900-9dea-11ea-8fba-2424dcdd07c9.png)

I am using `cookie-session`, but I believe it is to do with the length. The string I am trying to set is 4672 bytes, not including the surrounding Set-cookie syntax.

Researching it looks like Chrome only support 4 kb http://browsercookielimits.squawky.net/
> If all you care about is the conclusion, well here it is: If you want to support most browsers, then don't exceed 50 cookies per domain, and don't exceed 4093 bytes per domain (i.e. total size of all cookies <= 4093 bytes)
```
18:19:25.219: Starting
18:19:33.258: Guessing Max Cookie Size Per Cookie: 4096 bytes
```

I looked in the code and it does not look like there is code to do this error handling?

**Comment by dougwilson** [comment]
There is no error handling around this, as not all clients have the same length limitations. There is no limitation in the specification itself.

**Comment by kevinsimper** [comment]
@dougwilson So the best we can do is just to let users of this library themselves find out that a cookie is too long for the browser they try to support? How would they know that this is probrably the reason?

**Comment by dougwilson** [comment]
It is already clearly noted in the readme for the module you are using: https://github.com/expressjs/cookie-session/blob/master/README.md#max-cookie-size

**Comment by kevinsimper** [comment]
@dougwilson Really sorry, I overlooked that, thank you a lot! I searched for the phrase "This Set-Cookie had invalid syntax", but did not find any results here in this repo or in that.
