### ISSUE TITLE
Getting cookies of a request without having to pass response argument

### ISSUE THREAD

**Issue by joaopaulobdac** [pillarjs/cookies#127]
Hi! I need to get a certain cookie when the server emits the 'upgrade' event:

```javascript
server.on('upgrade', (request: IncomingMessage, socket: Socket, head: Buffer) => {
    // get request cookie here
})
```

Is it possible to do this? From what I can see inspecting the source code it should be, but if I emit the response parameter typescript complains. Is this a @types/cookies issue then?

**Comment by dougwilson** [comment]
We have a lower level module mode made for your use case, does that work for you? https://github.com/jshttp/cookie

**Comment by joaopaulobdac** [comment]
Great! Thank you.
