### ISSUE TITLE
set cookie with ";" is broken and the "signed" property returns undefined

### ISSUE THREAD

**Issue by pantchox** [pillarjs/cookies#132]
example (untested) code to explain the issue:
```
const value = 'this is my 1st paragraph; this is my second';
cookies.set('mycookie', value, {signed:true});
...
...
console.log(cookies.get('mycookie', {signed:true})); // logs out undefined
````
these issues occur:
1. the value of the cookie is saved as 'this is my 1st paragraph' and being cut by the ";" char. I assume because this is the character that splits between cookies when parsing.
2. due to the invalid cookie that is being saved, the added "mycookie.sig" hash is based on the correct full string - which is correct. but due to the issue #1 the hash is failing which result "cookies.get" to return undefined since the hash failed on the invalid saved cookie.

hope this is clear.

I know that you should encode/decode on set/get of the cookies, but i think that in the case of ";" it needs to be handled - very confusing for users.

thanks.

**Comment by dougwilson** [comment]
Hi @pantchox thanks for the report. You are correct; we need to throw on the `;` character being in the cookie name or value just like we do on the other invalid characters.

**Comment by pantchox** [comment]
as a workaround of course using an encode/decode works for now.
