### ISSUE TITLE
Release sameSite = none PR

### ISSUE THREAD

**Issue by dustin-H** [pillarjs/cookies#134]
Hi there,

about two years ago`v0.8.0` was released which should include the `sameSite` option value `none`:

See: 
https://github.com/pillarjs/cookies/pull/111
https://github.com/pillarjs/cookies/commit/fac05de8dfa77d722dac5237f0d8c54b6e0222ac

However, looking at the latest version in npm this feature is missing:
https://www.npmjs.com/package/cookies/v/0.8.0

Could anyone please release the latest master to npm?

**Comment by panva** [comment]
The feature is not missing. It is only lacking docs in the released README.

**Comment by dustin-H** [comment]
You're right. I had the wrong version in my project and thought it's the latest, as the docs on npm are the also not mentioning `sameSite=none`.

Sorry for my false assumption.

A release would nevertheless be useful as the docs are also already fixed:
https://github.com/pillarjs/cookies/commit/d2111627e8ff2e29f90e75d1f1cc4164c5a07a3f

**Comment by dougwilson** [comment]
Closed as already released. We do not make doc only releases. One day if nom let us update does without a release that would be swell.
