### ISSUE TITLE
Using this with Http2stream

### ISSUE THREAD

**Issue by nielsnl68** [pillarjs/cookies#136]
I wand to use this lib together with Node js Http/2 lib.

How can i do this properly?

**Comment by dougwilson** [comment]
See #99

**Comment by nielsnl68** [comment]
Altrough i saw that PR but i have no clue how to read it and see only tests.
I dont use express only vanilla, http2

**Comment by dougwilson** [comment]
That was the PR that someone was working with http2 and thia module. If that doesn't answer it, then please feel free to contribute an answer.
