### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by GregTCLTK** [pillarjs/cookies#139]
Hello,

Please [migrate](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) your repository to [travis-ci.com](https://www.travis-ci.com/) since travis-ci.org merged into it.

**Comment by dougwilson** [comment]
I am still waiting for my open source credits to be applied to the account. Until then I don't have credits to run the builds. Once there are credits it will be migrated 👍
