### ISSUE TITLE
make setHeader compatible with fastify reply (patch included)

### ISSUE THREAD

**Issue by mariusa** [pillarjs/cookies#144]
Instead of `res.setHeader`, fastify uses `reply.header("Content-Type", "application/json; charset=utf-8")`

http://expressjs.com/en/4x/api.html#res.set
https://www.fastify.io/docs/latest/Reference/Reply/#headerkey-value

Please make setting headers compatible with fastify too. 
Instead of this line
https://github.com/pillarjs/cookies/blob/7d6ac6015c8981b6020fb835d17b69881bf01a23/index.js#L115
use
```
  var setHeader = null
  if (typeof res.set == 'function') {
  	setHeader = http.OutgoingMessage.prototype.setHeader
  } else if (typeof res.setHeader == 'function') {
  	setHeader = res.setHeader
  } else if (typeof res.header == 'function') {
  	//fastify 
  	res.header('Set-Cookie', headers)
  	return this
  }  
  setHeader.call(res, 'Set-Cookie', headers)
  return this
```

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble. It seems like you are just passing in the wrong object for Fastify

https://github.com/pillarjs/cookies#new-cookiesrequest-response--options

> The request argument is a Node.js HTTP incoming request object and the response argument is a Node.js HTTP server response object.

So for Fastify, this should be `cookies = new Cookies(req.raw, reply.raw)`. I hope this helps!

**Comment by mariusa** [comment]
Thank you, Doug! That helps!
