### ISSUE TITLE
Using "signed: ture" will set two cookies? 

### ISSUE THREAD

**Issue by wlcharlie** [pillarjs/cookies#146]
Hi!
I was using signed to encrypt the value, but i found out that once i set signed to true
it will set two cookie
one without signed value
one with signed value

is this behaviour normal? thanks if reply

CODE:
```
const cookies = new Cookies(req, res, { keys: process.env.C_KEY.split(",") })

cookies.set("kk", "55", { signed: true })
```
IMAGE:
![image](https://user-images.githubusercontent.com/77925413/154607397-2d6dac93-3a56-43bc-91cb-f674883338e1.png)

**Comment by dougwilson** [comment]
Yes, that is the behavior documented in the readme:

> Unobtrusive: Signed cookies are stored the same way as unsigned cookies, instead of in an obfuscated signing format. An additional signature cookie is stored for each signed cookie, using a standard naming convention (cookie-name.sig). This allows other libraries to access the original cookies without having to know the signing mechanism.

**Comment by wlcharlie** [comment]
@dougwilson Thanks for quick reply.
since i am trying to store a jwt, wondering isn't this mean that the unsigned value will be exposed?

**Comment by dougwilson** [comment]
Signing will always expose the original. It is encryption that would hide the original value, not signing.
