### ISSUE TITLE
missing cookie option "Priority"

### ISSUE THREAD

**Issue by UROjQ6r80p** [pillarjs/cookies#147]
Currently there is no option to add "Priority" flag to a cookie.

"Priority" flag is supported in Chromium based browsers which is used by majority of web, and "Priority=High" could prevent for example a long lasting session cookie from being purged by newer analytics/ad cookies (a lot of websites use ads as their main revenue source and these ad scripts inject lots of new and big cookies per request).

It's not a very common scenario but could be useful and allow a more control over cookies.

**Comment by dougwilson** [comment]
This has been added to the 0.9.0 version of this module.
