### ISSUE TITLE
Get a cookie in 2023

### ISSUE THREAD

**Issue by msf-caesar** [pillarjs/cookies#149]
### Get a cookie in 2023

I propose to implement a new function to extract the value of a cookie in a simpler and more efficient way. This solution will simplify the process and significantly improve the way I get the cookie value.

![image](https://user-images.githubusercontent.com/113716133/209986020-f1aa6327-8442-4f66-9905-0ff61010b155.png)

**Comment by dougwilson** [comment]
Hello, and thank you for your issue. Unfortunately I think you may have opened this on the wrong repository. This is a Node.js module for the server, which does not have `document.cookie` like the web browser does. Using `document.cookie` does not work in Node.js and is out of scope for this module, which does not target web browsers. You'll need to use a module suited for the web browser.
