### ISSUE TITLE
secure check

### ISSUE THREAD

**Issue by michaelwittig** [pillarjs/cookies#15]
hi.

I have a problem with line 49 in lib/cookies.js:
if (!secure && opts && opts.secure) throw new Error("Cannot send secure cookie over unencrypted socket")

my node workers run in http mode because i handle SSL with stunnel before the requests enter haproxy where they are routed to my machines.

Are you happy with an option called secureProxy or something like this?

**Comment by robertjd** [comment]
I think this option should be called "force secure", as the library is not doing anything to determine if you are behind a proxy.

**Comment by dougwilson** [comment]
Hi @robertjd , as this issue is from about 3 years ago, it's considered stale and archived. Please open a new issue if it's still an issue for you!
