### ISSUE TITLE
How to set SameSite attribute for .sig?

### ISSUE THREAD

**Issue by RevealedFrom** [pillarjs/cookies#150]
I have a need to set the `SameSite` and `Secure` attributes for the .sig cookie to make a CORS request. 

The specific cookie I am interested in is `session` (in the package `cookie-session`). I could manually reissue the current value of `session` and set the aforementioned attributes, but how do I also set them for `session.sig` that is generated internally by the `cookies` module?

**Comment by dougwilson** [comment]
The `.sig` is set with all the same attributes as the main cookie...

```js
var cookies = require('cookies')
var express = require('express')

var app = express()

app.use(cookies.express(['foobar']))
app.get('/', function (req, res, next) {
  res.cookies.set('foo', 'bar', { sameSite: true, signed: true })
  res.end()
})

app.listen(3000)
```

```
$ node app &
[1] 167

$ curl -I http://localhost:3000
HTTP/1.1 200 OK
X-Powered-By: Express
Set-Cookie: foo=bar; path=/; samesite=strict; httponly
Set-Cookie: foo.sig=Cg2ltiMAfmwuSsOKd14XlYuTzAc; path=/; samesite=strict; httponly
Date: Thu, 13 Apr 2023 03:24:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
