### ISSUE TITLE
secure cookies behind load balancer

### ISSUE THREAD

**Issue by robrich** [pillarjs/cookies#46]
If https terminates at the load balancer, and thus node is not running https, I can't use secure cookies.  Would you accept a PR to enable an option to override https://github.com/expressjs/cookies/blob/master/lib/cookies.js#L60?

**Comment by apendua** [comment]
The problem here is that the check for "security" does not really make sense because there's just not enough information in the application itself to know if the request will be delivered to the user encrypted or not. I think it's bad logic and should be removed.

**Comment by apendua** [comment]
Is there any chance this will be fixed soon?
