### ISSUE TITLE
Example in the README is not working

### ISSUE THREAD

**Issue by ishan1608** [pillarjs/cookies#56]
Hello Sir

Thank you for taking the effort to create cookies (module).
I would like to point out that the example in the README is fine but it doesn't works if a user copy pastes them and tries to run the server.
These are the issues :
1. keys is not defined
2. assert is not defined
3. exception handling is not done
4. server is created but not listening on a port
5. It is nowhere mentioned that the expected use of the server is to first send a request to '/set'

The solutions: 
1. Installing keygrip and creating keys
    `npm install keygrip`
    `var keygrip = require("keygrip")`
    `var keys = keygrip(["SEKRIT2", "SEKRIT1"], 'sha256', 'hex')`
2. Including assert module
    `var assert = require("assert")`
3. putting the assertion part in try catch
    `<Copying pasting the code here will make this too long>`
4. Adding a .listen to server
    `}).listen(3000);`
5. Adding some html to let the user click and set the cookies
    `<Copying pasting the code here will make this too long>`
I have done all this and made a gist of https://gist.github.com/ishanatmuz/9b87247e129513367cef.

If you think that these changes are important, then please add them to the README or in a separate Example folder.
If you allow I will be more than happy to post a Pull Request for the same, with whatever you want (README changes, Example folder anything else).

**Comment by dougwilson** [comment]
The current example is just ridiculous and just needs a rewrite to a real example of using the module, then like half explaining the module using asserts.
