### ISSUE TITLE
Sets two cookies per set?

### ISSUE THREAD

**Issue by Xaxatix** [pillarjs/cookies#57]
I'm using Koajs, but I saw this is the middleware they use to handle cookies, so I'm posting the issue here. I tried tracing the issue, but to no avail. I'm not sure if this is intended, but it most likely seems like it shouldn't be creating 2 cookies.

This is the code I use to set a cookie.
```javascript
this.cookies.set('auth', cookieValue, {
  signed: true,
  httpOnly: true,
  maxAge: 1000 * 60 * 3
});
```

But then when I check my browser's resource cache there are 2 cookies set - one of them is even unsigned.
![cookie](https://cloud.githubusercontent.com/assets/6862136/7554862/79d97036-f741-11e4-8a1b-b00931114fa6.png)

**Comment by dead-horse** [comment]
`auth.sig` is a signature of `auth` to ensure user can not modify the cookie in client side,(server will check `auth.sig`). 

you won't get cookie `auth.sig` if `signed` is false.

**Comment by Xaxatix** [comment]
I kinda got that while tracing the problem. But why is there an unsigned one as well? Isn't the whole point of signed cookies to prevent the client from viewing (raw/unsigned) contents of the cookie?

**Comment by dead-horse** [comment]
not for now, but maybe it can be added in 1.0 ?
/cc @dougwilson @jonathanong

**Comment by Xaxatix** [comment]
Well that was what I was concerned with, thank you for letting me know. Hope to see 1.0 sometime soon. Have a good day.

**Comment by dougwilson** [comment]
Signed cookies are in the clear but contain a signature. Encrypted cookies are, well, encrypted. All signing does it allow for verification that the client has not tampered the value. For example you store some ID number in the cookie. It's not secret and does not need the large overhead of encryption, but you don't want the user to start sending you different ID numbers (think session ID and trying to hunt for a random person's session by ID).

**Comment by Xaxatix** [comment]
Ah, I understand better now. Just ran a couple small tests (with httpOnly set to false) to see when a cookie gets invalidated and it makes more sense now. Sorry for posting again on a 'closed' issue, but do you have any plans for encrypted cookies for 1.0?

**Comment by dougwilson** [comment]
Yes, there will be encrypted cookies. It was delayed forever because of keygrip, which I just resumed working on yesterday, in fact.

**Comment by Xaxatix** [comment]
Great news, even though I now see why signed cookies are somewhat of a replacement for encrypted ones. Thank you for your time and the updates, and keep at it.

**Comment by Xaxatix** [comment]
Very last thing (posting it as a new reply, because I don't know if you get notifications for edited replies) - it would be useful to include this feature from [mozilla's client-sessions](https://github.com/mozilla/node-client-sessions). 

```javascript
  activeDuration: 1000 * 60 * 5 // if expiresIn < activeDuration, the session will be extended 
```

Alright, I'm done with this issue.

**Comment by dougwilson** [comment]
Yes, github does not email for edited posts. So you are talking beyond this library now; this is simply a cookie reading/writing library. Session management is beyond this module.
