### ISSUE TITLE
ability to get cookie from response

### ISSUE THREAD

**Issue by goldensunliu** [pillarjs/cookies#63]
currently .get is getting from request. It would be awesome if it can also take account of what has been set during the request on its response:

```
cookies = new Cookies(req, res);
cookies.set( "unsigned", "foo", { httpOnly: false } );
console.log cookies.get( "unsigned" );
```
this will log ```undefined```

**Comment by jonathanong** [comment]
what's the use-case for this?

**Comment by dougwilson** [comment]
Closing issue due to lack of response.
