### ISSUE TITLE
Cookie version 1

### ISSUE THREAD

**Issue by mderazon** [pillarjs/cookies#64]
I have a client that sends cookies in version 1 format, `$Version: "1"`

I noticed that all cookies sent with version 1 are quoted i.e. `name: "value"`.

Does this module parse them correctly as well ? I had some problems using version 1 cookies with [mozilla/node-client-sessions](https://github.com/mozilla/node-client-sessions), specifically, the session cookie was not being parsed correctly because of the quotation marks

**Comment by dougwilson** [comment]
Weird. Is there some kind of RFC that explains how this version 1 works?

**Comment by mderazon** [comment]
@dougwilson I think it's [RFC-2965](https://www.ietf.org/rfc/rfc2965.txt)

**Comment by dougwilson** [comment]
Yea, I see it right at the top: `value       =     token | quoted-string`

**Comment by naruaway** [comment]
Hi! I want to let this library to return unquoted value for cookies to make the behavior of koa aligned with other popular frameworks like Django or Express.
I created [a PR](https://github.com/pillarjs/cookies/pull/140) to automatically strip quotes for cookie values. Hopefully it could also solve this issue.
