### ISSUE TITLE
How to use secure cookies behind an SSL load balancer

### ISSUE THREAD

**Issue by scriby** [pillarjs/cookies#71]
In the past I had used the secureProxy setting to allow the cookies module to write secure cookies when running behind a load balancer that was handling SSL. Now that the option is removed I am getting an error indicating that I can't set secure cookies on an insecure connection.

Is there some way to work around that now?

**Comment by scriby** [comment]
I found the documentation on how to do it now. Looks like you have to pass something to the cookie constructor now.

**Comment by DavidTPate** [comment]
For those that find this issue in the future. There's a note [here](https://github.com/expressjs/session/tree/005078aaada837d2a57e7324986ead60bf326e84#cookie-options) about how you setup express.

Specifically:
> If `secure` is set, and you access your site over HTTP, the cookie will not be set. If you have your node.js behind a proxy and are using `secure: true`, you need to set "trust proxy" in express

```js
if (app.get('env') === 'production') {
  app.set('trust proxy', 1) // trust first proxy
  sess.cookie.secure = true // serve secure cookies
}
```

**Comment by dougwilson** [comment]
Hi @scriby, you should not be getting any error and nothing has actually been removed. Are you talking about the deprecation message in the new version? It should not have changed the behavior of your existing code and you can always suppress the message with `node --no-deprecation` or setting the environment variable `NO_DEPRECATION=cookies` while you figure out the best way to take advantage of the new feature and migrate away from a feature that will eventually be removed.
