### ISSUE TITLE
Whether to support Chinese?

### ISSUE THREAD

**Issue by occultskyrong** [pillarjs/cookies#72]
Today I use this module set a cookie to be found when the writing is Chinese, 
it will error "TypeError: argument value is invalid".

Later I discovered that such a line of code,
`var fieldContentRegExp = /^[\u0009\u0020-\u007e\u0080-\u00ff]+$/;`

So I think that this module does not support the direct use of Chinese were cookies.set.
The Chinese need to escape to the corresponding unicode coding can write a cookie.

(先把中文转义为Unicode字符，然后再使用cookies写入cookie即可)    just like

`cookies.set("userName", encodeURI('中文名字'), {..});`

**Comment by dougwilson** [comment]
Hi! This module supports any language, it just leaves the decision of how you want to encode the value up to you to do, so this module can easily be used across languages which may enforce a specific encoding.

The regular expression you pointed to is just to validate the restriction on header content as set out by the HTTP RFC 7230, not by us.

Using urlencoding or base64 encoding are common ways to encore your values before putting in the cookie.

**Comment by occultskyrong** [comment]
thank you, I will see this document .
