### ISSUE TITLE
Signed option throws exception

### ISSUE THREAD

**Issue by ihabZhaika** [pillarjs/cookies#73]
hi,
i wanted to make a signed cookie , but throws this exception
```
this.keys.sign is not a function  at Cookies.set  , \node_modules\cookies\lib\cookies.js:94:30)
```
The  Used code : 
```js
  var co = new Cookies(request,response , {keys:"somekeys" });
                co.set("access","allowed",{signed:true});

```

**Comment by dougwilson** [comment]
Hi! The issue is that your value given to the `keys` option is not a valid value. From the documentation:

> A Keygrip object or an array of keys can optionally be passed as options.keys to enable cryptographic signing based on SHA1 HMAC, using rotated credentials.

This means that your value needs to be a Keygrip object or an array of strings. A simple tweak to your code should fix this by putting your string into an array:

```js
var co = new Cookies(request, response, {keys: ["somekey"]});
```

I hope that helps!

**Comment by ihabZhaika** [comment]
ok thanx
