### ISSUE TITLE
does'nt support chinese

### ISSUE THREAD

**Issue by qingmingsang** [pillarjs/cookies#78]
```
var reg = /^[\u0009\u0020-\u007e\u0080-\u00ff]+$/;
console.log(reg.test('中文'))//false
```

**Comment by dougwilson** [comment]
Because the field value cannot have those characters. This module expects you to encode your data to use it, i.e. base64 your Chinese characters or something.

**Comment by qingmingsang** [comment]
thx

i think 
```
encodeURIComponent()
```
is useful
