### ISSUE TITLE
Unexpected token % in JSON at position 1 at Object.parse

### ISSUE THREAD

**Issue by eaharonoff** [pillarjs/cookies#90]
Hey there,
Is it possible to retrieve cookies whose value is an object (assuming the object is stringified + URI encoded)? Right now I am using this solution `JSON.parse(decodeURIComponent('key'))` but was wondering if there was a solution on your end...

**Comment by dougwilson** [comment]
It should be possible; this module doesn't touch the value of your cookie: you just hand it a string and it'll set that and you'll get back the same string. Can you provide an example of what string you are using that is giving you the error in your subject (and perhaps the stack trace)? Or at least some code examples to better understand your question / issue.

**Comment by eaharonoff** [comment]
Sure.
Background: 
The cookie's value is set using https://github.com/ScottHamper/Cookies by the client, and then retrieved using [koa's context](https://github.com/koajs/koa/blob/master/docs/api/context.md) on the server. To set the cookie, I needed to stringify the object beforehand, and then https://github.com/ScottHamper/Cookies URI encodes the value. The code ends up looking 
something like this: 
```
onClickExample(value) {
  const cookies = new Cookies(); // Uses ScottHamper/Cookies library
  let valueString = JSON.stringify(value);
  cookies.set('key', valueString); // Cookie value is set to {%22id%22:6%2C%22city%22:%22Washington%2C%20DC%22%2C%22waitlisted%22:0}
}

retrieveServerSideExample(ctx) {
  try {
    const cookies = new KoaCookies({ ctx }); // Koa Context using pillarjs/cookies
    const valueCookie = JSON.parse(cookies.get('key')); 
    // do something with cookie
   }
   catch (e) {
    debug('koa')('Error initializing city: %o', e);
 }
```
The error message returned is `koa Error initializing city: SyntaxError: Unexpected token % in JSON at position 1 at Object.parse (native)`

I can avoid this by wrapping `valueCookie` like this `JSON.parse(decodeURIComponent(valueCookie))` but was wondering if there were any plans to have the object decoded before the value gets called?

**Comment by dougwilson** [comment]
Gotcha. The issue is that there are many ways you an encode a cookie's value, where URI encoding is just one possible way. This module just provides the raw string in the cookie so users can read the value and perform whatever their specific encoding / decoding routines need to be. There are no plans to add any kind of built-in encoding or decoding to this module.

**Comment by eaharonoff** [comment]
Cool! That's all I wanted to know. Thanks anyway!

**Comment by dougwilson** [comment]
No problem :) !
