### ISSUE TITLE
secure option & SNI

### ISSUE THREAD

**Issue by talkingtab** [pillarjs/cookies#92]
I have a koa server running behind http-proxy which provides SNI so I can run multiple websites on one ip address. cookies won't set secure and throws and error because the protocol is secure. I can't find anyway to fix this other than changing the code directly. Is there facility in koa or cookies to disable this test?

**Comment by dougwilson** [comment]
When you create a new cookies object (https://github.com/pillarjs/cookies/blob/master/README.md#cookies--new-cookies-request-response--options--) are you passing in thr option "secure: true"?

**Comment by dougwilson** [comment]
Setting that option is the best method when you know your app is only accessible from behind the ssl terminator. If you don't set that option this module will auto detect as documented at https://github.com/pillarjs/cookies/blob/master/README.md#secure-cookies

**Comment by talkingtab** [comment]
I did set api.proxy = true in koa, but it seemed to make no difference. Maybe the X-Forwarded-Proto header is not being set, I'll verify that. Thanks!

**Comment by dougwilson** [comment]
Yea, that could be. You can always just set secure: true in the consrructor here to simply disable the check as well.

**Comment by talkingtab** [comment]
Maybe I'm missing something, but it looks like koa.js initializes Cookies and I did not see a way to pass a Cookie option to koa. I'm trying to do this:
`ctx.cookies.set(nameg, token, { domain, path: '/', httponly: true, maxage: 3600000, secure: true});`

**Comment by talkingtab** [comment]
That was the problem. I'm using http-proxy and when I set the X-Frowarded-Proto header and it works like a charm. Thank you!

**Comment by dougwilson** [comment]
Gotcha. So I'm not sure what you would like this module to do. I know you opened the issue here. Perhaps you can define what you're looking for me to do to help me out here.

**Comment by talkingtab** [comment]
Maybe this is more an issue for koa because AFAIK you can't get to the set an option in koa that will get passed to the cookie module.  

You could document that app.proxy = true depends on the X-Frowarded-Proto but I'm not sure its worth it. 

But thanks for all the work you have done on this and your willingness to help

**Comment by dougwilson** [comment]
> You could document that app.proxy = true depends on the X-Frowarded-Proto but I'm not sure its worth it.

That is exactly what is in the readme already. Can you clarify, please?

**Comment by talkingtab** [comment]
Duh, You are right. The only real problem I had was that the proxy module I used doesn't automatically put the headers in for you.

**Comment by dougwilson** [comment]
Gotcha. I'm happy to add whatever to the readme that will help, which is how Koa got in there because they use this module.

**Comment by talkingtab** [comment]
Let me think on it and if I can think of anything constructive I will get
back to you.

On October 7, 2017 at 6:40:16 PM, Douglas Wilson (notifications@github.com)
wrote:

Gotcha. I'm happy to add whatever to the readme that will help, which is
how Koa got in there because they use this module.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/pillarjs/cookies/issues/92#issuecomment-334970488>, or mute
the thread
