### ISSUE TITLE
Signed cookies with double quoted values 

### ISSUE THREAD

**Issue by markmeyerphoto** [pillarjs/cookies#93]
I'm having an issues where I set cookies on a response to a service (Twilio). The  cookie header I am getting back from them looks like this: 

    cookie: '$Version=1; session="eyJrbm93bl9jYXNlIjpmYWxzZSwiY2FzZV9pZCI6IjEyMzQ1NjcifQ=="; 
    $Path="/"; $Domain=xx.xx.xx.xxx; $Version=1; session.sig=DasSRyvhWnjYpCF0VKJIsrvbXAY; 
    $Path="/"; $Domain= xx.xx.xx.xxx',

With the value for `session` wrapped in double quotes. This works fine for regular cookies, but it fails when using signed cookies. It looks like the module is comparing the entire string's signature, including the quotes, with the signature created from the unquoted value I'm sending. Double quoted cookie octets are okay according to RFC 6265, but of course it says nothing about what the behavior should be with detecting tampering -- whether we should compared the entire value or octet. 

Is this expected behavior? And if so, since I can't control the cookie coming back from Twilio, is there a work around?

**Comment by dougwilson** [comment]
Ah, I see there is indeed an issue for this already: #64 . A PR to add cookie version 1 support would be welcome, and I think that would fix your issue.

**Comment by dougwilson** [comment]
Closing as a duplicate since there was never any response.
